config dentro de DOCKER

diff --git a/client-web/Dockerfile b/client-web/Dockerfile
--- a/client-web/Dockerfile
+++ b/client-web/Dockerfile
@@ -1,24 +1,81 @@
-FROM node:18-alpine
+FROM node:18-alpine AS base
 
-# Establecer directorio de trabajo
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-RUN npm install -g nextui-cli
+# Install dependencies based on the preferred package manager
+COPY package.json package-lock.json* ./
+RUN npm i
+  # if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  # if [ -f package-lock.json ]; then npm ci; \
+  # elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  # else echo "Lockfile not found." && exit 1; \
+  # fi
 
-# Copiar los archivos de package.json y package-lock.json
-COPY package*.json ./
 
-# Instalar dependencias
-RUN npm install
-
-# Copiar el resto de la aplicación
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-# Construir la aplicación para producción
-# RUN npm run build
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED=1
 
-# Exponer el puerto 3000 (puerto predeterminado para Next.js)
+ARG NEXT_PUBLIC_SERVER_URI=http://api.rallycronos.com/
+ARG NEXT_PUBLIC_CLIENT_SECRET=g179NrxEhLKvZTNDAZy6muwpR8TQ7WPoWuIJr6tz
+ARG NEXT_PUBLIC_SECURE_KEY=7mARe8nTS5CWefBEaHP6jzIRnDGM44NXiWuAvkNJ
+ARG NEXT_PUBLIC_GA_TRACKING_ID=G-2SKBJB5HQ0
+
+
+ENV NEXT_PUBLIC_SERVER_URI=$NEXT_PUBLIC_SERVER_URI
+ENV NEXT_PUBLIC_CLIENT_SECRET=$NEXT_PUBLIC_CLIENT_SECRET
+ENV NEXT_PUBLIC_SECURE_KEY=$NEXT_PUBLIC_SECURE_KEY
+ENV NEXT_PUBLIC_GA_TRACKING_ID=$NEXT_PUBLIC_GA_TRACKING_ID
+
+RUN npm run build
+  # if [ -f yarn.lock ]; then yarn run build; \
+  # elif [ -f package-lock.json ]; then npm run build; \
+  # elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  # else echo "Lockfile not found." && exit 1; \
+  # fi
+
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV=production
+# ENV NEXT_PUBLIC_SERVER_URI=NEXT_PUBLIC_SERVER_URI
+
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED=1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
 EXPOSE 3000
 
-# Ejecutar la aplicación Next.js
-CMD ["npm", "start"]
+# ENV PORT=3000
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+# ENV HOSTNAME="0.0.0.0"
+# CMD ["node", "server.js"]
